### ISSUE TITLE
Header inconveniences

### ISSUE THREAD

**Issue by axblueblader** [huynhminhtufu/jiny#9]
1. Unexpected behavior:
- It was unexpected when ```ctx.headerParam("Uppercase-Header")``` didn't work because request headers are transformed to lower case. From documentation it seems it was intended, maybe headerParam should also lower case before retrieving? 
- However the headers in response object has casing and retrieving with ```res.getHeader``` respect casing as well.

2. HttpClient enhancement:
- Builder function for changing single header using lombok's ```@Singular``` annotation

**Comment by huynhminhtufu** [comment]
Cool, looking forward to your pull request @axblueblader 😄

**Comment by huynhminhtufu** [comment]
After check, the `HttpServer` has the same issue

[core/AbstractRequestBinder.java](https://github.com/huynhminhtufu/jiny/blob/master/src/main/java/com/jinyframework/core/AbstractRequestBinder.java#L113-L135) - need a toLowerCase() on methods's argument

Will fix in `0.2.8`
